export type Language = 'en' | 'zh';

export interface Translations {
  // App
  backToSearch: string;
  settings: string;
  
  // InputArea
  title: string;
  subtitle: string;
  inputPlaceholder: string;
  addButton: string;
  generateButton: string;
  generatingButton: string;
  generatingSubtext: string;
  
  // ApiKeyModal
  enterApiKey: string;
  requiredToGenerate: string;
  apiKeyLabel: string;
  geminiApiKeyLabel: string;
  apiKeyRequired: string;
  apiKeySecurityWarning: string;
  baseUrlLabel: string;
  baseUrlOptional: string;
  modelNameLabel: string;
  modelNameOptional: string;
  modelNameHint: string;
  cancel: string;
  saveKey: string;
  
  // Error messages
  errorGenerate: string;
  
  // Language
  language: string;
  english: string;
  chinese: string;
  
  // Wikipedia attribution
  wikiAttribution: string;
  aiGeneratedDisclaimer: string;
  
  // Sample queries
  sampleQueries: string[][];
}

export const translations: Record<Language, Translations> = {
  en: {
    // App
    backToSearch: 'Back to search',
    settings: 'Settings',
    
    // InputArea
    title: 'What Happened When...',
    subtitle: 'Merge histories. Discover connections.',
    inputPlaceholder: 'Type and press Enter...',
    addButton: 'Add',
    generateButton: 'Generate Timeline',
    generatingButton: 'Weaving Timelines...',
    generatingSubtext: 'This may take a moment.',
    
    // ApiKeyModal
    enterApiKey: 'Enter API Key',
    requiredToGenerate: 'Required to generate timelines',
    apiKeyLabel: 'API Key',
    geminiApiKeyLabel: 'Google Gemini API Key',
    apiKeyRequired: 'API Key is required',
    apiKeySecurityWarning: 'Your API key will be stored in plain text in your browser\'s local storage. Anyone with access to your browser can read it. Never save your API key on public, shared, or untrusted devices.',
    baseUrlLabel: 'Base URL',
    baseUrlOptional: 'Base URL (Optional)',
    modelNameLabel: 'Model Name',
    modelNameOptional: 'Model Name (Optional)',
    modelNameHint: 'Leave blank to use default.',
    cancel: 'Cancel',
    saveKey: 'Save Key',
    
    // Error messages
    errorGenerate: 'Failed to generate timeline. Please check your API key and try again.',
    
    // Language
    language: 'Language',
    english: 'English',
    chinese: '中文',
    
    // Wikipedia attribution
    wikiAttribution: 'Content sourced from Wikipedia',
    aiGeneratedDisclaimer: 'Timeline generated by AI. AI can make mistakes.',
    
    // Sample queries
    sampleQueries: [
      ["Apple Inc.", "Microsoft", "Google"],
      ["Roman Empire", "Han Dynasty"],
      ["SpaceX", "NASA", "Blue Origin"],
      ["The Beatles", "Queen", "Rolling Stones"]
    ],
  },
  zh: {
    // App
    backToSearch: '返回搜索',
    settings: '设置',
    
    // InputArea
    title: '历史时间线...',
    subtitle: '合并历史，发现联系。',
    inputPlaceholder: '输入后按回车...',
    addButton: '添加',
    generateButton: '生成时间线',
    generatingButton: '正在生成时间线...',
    generatingSubtext: '这可能需要一些时间。',
    
    // ApiKeyModal
    enterApiKey: '输入 API 密钥',
    requiredToGenerate: '生成时间线所需',
    apiKeyLabel: 'API 密钥',
    geminiApiKeyLabel: 'Google Gemini API 密钥',
    apiKeyRequired: 'API 密钥是必需的',
    apiKeySecurityWarning: '您的 API 密钥将以明文形式存储在浏览器的本地存储中。任何能访问您浏览器的人都可以读取它。切勿在公共、共享或不受信任的设备上保存您的 API 密钥。',
    baseUrlLabel: '基础 URL',
    baseUrlOptional: '基础 URL（可选）',
    modelNameLabel: '模型名称',
    modelNameOptional: '模型名称（可选）',
    modelNameHint: '留空以使用默认值。',
    cancel: '取消',
    saveKey: '保存密钥',
    
    // Error messages
    errorGenerate: '生成时间线失败。请检查您的 API 密钥并重试。',
    
    // Language
    language: '语言',
    english: 'English',
    chinese: '中文',
    
    // Wikipedia attribution
    wikiAttribution: '内容来源于维基百科',
    aiGeneratedDisclaimer: '时间线由AI生成。AI也可能会犯错误。',
    
    // Sample queries
    sampleQueries: [
      ["苹果公司", "微软", "谷歌"],
      ["罗马帝国", "汉朝"],
      ["SpaceX", "NASA", "蓝色起源"],
      ["披头士", "皇后乐队", "滚石乐队"]
    ],
  },
};

export const getTranslations = (lang: Language): Translations => {
  return translations[lang];
};
